name: Build woff2 for all platforms

on: workflow_dispatch

jobs:
    build:
        strategy:
            matrix:
             target: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.target }}
        steps:
            - uses: actions/checkout@v4
              with:
                repository: 'google/woff2'
                submodules: true
            - run: make clean all
            - run: ls -l
