name: Build woff2 for all platforms

on: push

jobs:
    build:
        strategy:
            matrix:
             target: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.target }}
        steps:
            - uses: actions/checkout@v4
              with:
                repository: 'google/woff2'
                submodules: true
            - name: Build Brotli
              run: |
                  cd brotli
                  mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Release
                  cmake --build .
                  cd ../..
            - run: |
                mkdir build
                cd build
                cmake .. \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DBROTLI_DIR=$GITHUB_WORKSPACE/brotli/build 
            - name: Build
              run: cmake --build build --config Release
            - run: ls -l
            - uses: actions/upload-artifact@v4
              with:
                name: woff2-${{matrix.target}}
                path: woff2_compress
